# docker-compose:
version: '3'
services:
  order-service:
    image: order-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  payment-service:
    image: payment-service:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    depends_on:
      - order-service



  postgres:
    container_name: postgres
    image: postgres:latest
    tty: true   # 1 of 2 requirement for detached mode
    stdin_open: true # 2 of 2 requirement for detached mode
    restart: always
    environment:
      POSTGRES_DB: opentelemetry
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  

