{
 "title": "Service Performance",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Payment Service Threads",
   "type": "gauge",
   "description": "Live threads count.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_peak{job=\"payment-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traces /payments/getAllOrders > 20 ms",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 0 },
   "targets": [
    { "maxDuration": "300ms", "minDuration": "20ms", "operation": "GET /payments/getAllOrders", "service": "payment-service" }
   ]
  },
  {
   "title": "High Latency Alerts for /payments/getAllOrders",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(http_server_duration_milliseconds_bucket{job=\"payment-service\", http_route=\"/payments/getAllOrders\"}[5m])) > 20",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Usage for Payment Service",
   "type": "stat",
   "description": "Total HTTP requests received per endpoint.",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{id=\"direct\", job=\"payment-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Request Timeline",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 15, "y": 5 },
   "targets": [
    {
     "expr": "http_client_duration_milliseconds_bucket{job=\"payment-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payment Service - CPU Usage",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 8 },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"payment-service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}