@startuml

!theme crt-amber

actor "DevOps" as ops
Actor "Grafana-UI" as UI
node "OTel Enabled - Observable pipeline" as pipeline{

frame "1-Jenkins OTel plug-in" {
    frame "2-Build" as build {
        component "Maven-OTelExtension" as mvn
        component "ShellScripts-otelCli" as cli
    }

     frame "3-Test" as test{
            component "JUnit-JupiterPlugIn" as junit
            component "ShellScripts-otelCli" as cli
        }

     frame "3-Test" as test{
                 component "JUnit-JupiterPlugIn" as junit
                 component "ShellScripts-otelCli" as cli
             }
     frame "4-Package" as package{
                      component "Artifactory-Filelog receiver" as jfrog
                  }
     frame "5-Deploy" as deploy{
                      component "Ansible-OTelCallBack" as ansible
                      component "ShellScripts-otelCli" as deploy_cli
                    }
    }
}

node "OpenTelemetry-Collector" as collector {
    frame "OTLP receiver"
    frame "Git Provider Receiver"
    frame "FileLog Receiver"
}

node "Observability BackEnd" as backend {
    database "Prometheus"
    database "Loki"
    database "Jaeger"
}

build --> test
test --> package
package --> deploy

ops-->pipeline
pipeline --> collector
collector -d-> backend
backend ---> UI

@enduml