@startuml
header @author: Chandu D , @created on: 02/03/2025
!theme crt-amber
footer  Page %page% of %lastpage%
title  Payment Service -> Order Service

skinparam {
'actorStyle awesome
'monochrome reverse
SequenceMessageAlignment direction
}

actor "HttpClient" as browser
participant "Payment-Service" as paymentService
participant "Orders-Service" as orderService
database  "Orders DB" as ordersDB

    group FetchOrders
        browser -> paymentService ++: GET allOrders to process Payment
        paymentService -> orderService ++: getAllOrders Pending Payment
        orderService -> ordersDB ++: query DB
        ordersDB -> orderService --: json Response
        orderService -> paymentService --: return allOrders PendingPayment
        paymentService -> browser --: response
    end

    group ProcessPayment
        browser -> paymentService ++ : processPayment/<orderID>
        paymentService -> paymentService ++: calculatePaymentForOrderID
        paymentService -> browser --: sendResponse
    end
@enduml