apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: collector
  name: collector
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: collector
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: collector
    spec:
      containers:
      - args:
        - --config=/etc/otelcol-contrib/otel-collector.yml
        image: otel/opentelemetry-collector-contrib:0.91.0
        imagePullPolicy: ""
        name: collector
        ports:
        - containerPort: 4317
        - containerPort: 4318
        - containerPort: 8889
        resources: {}
        volumeMounts:
        - mountPath: /etc/otelcol-contrib/otel-collector.yml
          name: collector-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: collector-claim0
        persistentVolumeClaim:
          claimName: collector-claim0
status: {}
